### ISSUE TITLE
Поменять адрес для шрифтов PTSans и PTMono в README.md

### ISSUE THREAD

**Issue by h714je** [Amet13/master-thesis#11]
По адресу `https://ftp.tw.freebsd.org/distfiles/xorg/font/{PTSansOFL,PTMonoOFL}.zip` уже нет этих шрифтов, надо бы их поменять. Например, на `https://ponce.cc/slackware/sources/repo/ttf-paratype-pt-fonts/{PTSansOFL,PTMonoOFL}.zip`. Или на какой-нибудь другой у которого больше доверия.

**Comment by Amet13** [comment]
Исправлено, спасибо.
https://github.com/Amet13/master-thesis/releases/tag/1.1.1
